
mutation CreateMovie($title: String!, $genre: String!, $imageUrl: String!) {
    insertIntoMovies(
        values: {
            id: "uuid.v4()",
            title: $title,
            genre: $genre,
            imageUrl: $imageUrl
        }
    ) {
        id
    }
}

mutation UpsertUser($username: String!) {
    upsertIntoUsers(
        values: {
            id: "auth.uid()",
            username: $username
        }
    ) {
        id
    }
}

mutation AddReview($movieId: String!, $rating: Int!, $reviewText: String!) {
    upsertIntoReviews(
        values: {
            userId: "auth.uid()",
            movieId: $movieId,
            rating: $rating,
            reviewText: $reviewText,
            reviewDate: "now()"
        }
    ) {
       userId
       movieId
    }
}

mutation DeleteReview($movieId: String!) {
    deleteFromReviews(
        filter: {
            userId: { eq: "auth.uid()" },
            movieId: { eq: $movieId }
        }
    ) {
        userId
        movieId
    }
}
