
mutation CreateMovie($title: String!, $year: Int, $genres: [String!], $imageUrl: String) {
  movie_insert(data: {
    id: "generate_uuid()",
    title: $title,
    year: $year,
    genres: $genres,
    imageUrl: $imageUrl
  }) {
    id
  }
}

mutation UpsertUser($id: UUID!, $username: String!) {
  user_upsert(data: {
    id: $id,
    username: $username
  }) {
    id
  }
}

mutation AddReview($movieId: UUID!, $userId: UUID!, $rating: Int, $reviewText: String) {
  review_upsert(data: {
    movieId: $movieId,
    userId: $userId,
    rating: $rating,
    reviewText: $reviewText,
    createdAt: "now()"
  }) {
    movieId,
    userId
  }
}


mutation DeleteReview($movieId: UUID!, $userId: UUID!) {
  review_delete(movieId: $movieId, userId: $userId) {
    movieId
    userId
  }
}
