
# Create a new movie
mutation CreateMovie($title: String!, $year: Int, $genres: [String], $imageUrl: String) {
  movie_insert(
    data: { id: { auto: "" }, title: $title, year: $year, genres: $genres, imageUrl: $imageUrl }
  ) {
    id
  }
}

# Create or update a user
mutation UpsertUser($id: String!, $username: String!) {
  user_upsert(
    data: { id: $id, username: $username }
  ){
    id
  }
}

# Add or update a review for a movie
mutation AddReview($movieId: String!, $userId: String!, $rating: Int, $reviewText: String) {
  review_upsert(
    data: {
      movieId: $movieId
      userId: $userId
      rating: $rating
      reviewText: $reviewText
      reviewDate: { auto: "" }
    }
  ) {
    movieId
    userId
  }
}

# Delete a review
mutation DeleteReview($movieId: String!, $userId: String!) {
  review_delete(
    filter: { _and: [{ movieId: { eq: $movieId } }, { userId: { eq: $userId } }] }
  ) {
    movieId
    userId
  }
}
