
query ListMovies {
  movies {
    id
    title
    imageUrl
    genre
  }
}

query GetMovieById($id: String!) {
  movies(id: { eq: $id }) {
    id
    title
    imageUrl
    genre
    reviews {
      reviewText
      reviewDate
      rating
      user {
        id
        username
      }
    }
  }
}

query ListUsers {
    users {
        id
        username
    }
}

query ListUserReviews {
  users(id: { eq: "auth.uid" }) {
    id
    username
    reviews {
      rating
      reviewDate
      reviewText
      movie {
        id
        title
      }
    }
  }
}

query SearchMovie($titleInput: String, $genre: String) {
    movies(filter: {
        title: { like: $titleInput },
        genre: { eq: $genre }
    }) {
        id
        title
        genre
        imageUrl
    }
}
