
# List all movies with their basic information
query ListMovies {
  movies {
    id
    title
    year
    genres
    imageUrl
  }
}

# Get a specific movie by its ID, including its reviews
query GetMovieById($movieId: String!) {
  movies(movieId: $movieId) {
    id
    title
    year
    genres
    imageUrl
    reviews {
      userId
      rating
      reviewText
      reviewDate
      user {
        username
      }
    }
  }
}

# List all users
query ListUsers {
    users {
        id
        username
    }
}


# List reviews for a specific user
query ListUserReviews($userId: String!) {
  users(userId: $userId) {
    id
    username
    reviews {
      rating
      reviewText
      reviewDate
      movie {
        id
        title
      }
    }
  }
}

# Search for movies based on title or genre
query SearchMovie($titleInput: String, $genre: String) {
  movies(
    filter: {
      _or: [{ title: { like: $titleInput } }, { genres: { contains: $genre } }]
    }
  ) {
    id
    title
    year
    genres
    imageUrl
  }
}
