
type Movie @table(name: "movies") {
  id: String! @pk
  title: String!
  year: Int
  genres: [String]
  imageUrl: String
  reviews: [Review] @relation(on: "movieId")
}

type User @table(name: "users") {
  id: String! @pk
  username: String!
  reviews: [Review] @relation(on: "userId")
}

type Review @table(name: "reviews") {
  movieId: String! @pk
  userId: String! @pk
  rating: Int
  reviewText: String
  reviewDate: Timestamp
}
