type Movie @table(name: "movies") {
  id: String! @pk
  title: String!
  genre: String
  imageUrl: String
  reviews: [Review] @relation(on: "movieId")
  metadata: MovieMetadata @relation(on: "id")
}

type MovieMetadata @table(name: "movie_metadata") {
  id: String! @pk
  releaseYear: Int
  description: String
  rating: Float
}

type Review @table(name: "reviews") {
  userId: String! @pk
  movieId: String! @pk
  reviewText: String
  rating: Int
  reviewDate: Timestamp! @default(expression: "CURRENT_TIMESTAMP")
  user: User! @relation(on: "userId")
  movie: Movie! @relation(on: "movieId")
}

type User @table(name: "users") {
  id: String! @pk @auth(claim: "uid")
  username: String!
  reviews: [Review] @relation(on: "userId")
}
